<?php
/**
 * Conteudo legado do site antigo (Wix), convertido para o tema.
 * Gerado automaticamente - nao editar a mao.
 */
return [
    [
        'tipo' => 'page',
        'slug' => '25a-feicoop',
        'titulo' => 'Especial 25 Anos',
        'arquivo' => '25a-feicoop.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => '27-feicoop-2021',
        'titulo' => '27ª FEICOOP - 2021',
        'arquivo' => '27-feicoop-2021.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => '28a-feicoop-2022',
        'titulo' => '28ª FEICOOP - 2022',
        'arquivo' => '28a-feicoop-2022.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => '31-feicoop',
        'titulo' => '31ª FEICOOP',
        'arquivo' => '31-feicoop.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-27a-feicoop',
        'titulo' => 'FEICOOP',
        'arquivo' => 'copia-27a-feicoop.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-27a-feicoop-feira-presencial',
        'titulo' => 'Orientação Card',
        'arquivo' => 'copia-27a-feicoop-feira-presencial.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-28a-feicoop-2022',
        'titulo' => '29ª FEICOOP | FEIRA INTERNACIONAL DO COOPERATIVISMO',
        'arquivo' => 'copia-28a-feicoop-2022.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-feicoop',
        'titulo' => 'FEICOOP 2021',
        'arquivo' => 'copia-feicoop.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'feicoop',
        'titulo' => '21ª FEICOOP',
        'arquivo' => 'feicoop.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'feicoop-presencial-2021',
        'titulo' => '27ª FEICOOP - Feira Presencial',
        'arquivo' => 'feicoop-presencial-2021.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'general-8',
        'titulo' => 'Programação Seminários 31ª FEICOOP',
        'arquivo' => 'general-8.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'general-8-1',
        'titulo' => 'Mapa 31ª FEICOOP',
        'arquivo' => 'general-8-1.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'projects-6',
        'titulo' => 'Programação Cultural 31ª FEICOOP',
        'arquivo' => 'projects-6.html',
        'grupo' => 'FEICOOP: edições e programações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-10',
        'titulo' => 'Feicoop irá sediar reunião temática da Convenção-Quadro para o controle do tabaco | projetoesperancacooesperanca',
        'arquivo' => 'carta-10.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-11',
        'titulo' => 'Feicoop irá sediar reunião temática da Convenção-Quadro para o controle do tabaco | projetoesperancacooesperanca',
        'arquivo' => 'carta-11.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-11-1',
        'titulo' => 'Feicoop irá sediar reunião temática da Convenção-Quadro para o controle do tabaco | projetoesperancacooesperanca',
        'arquivo' => 'carta-11-1.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-12',
        'titulo' => 'Feicoop irá sediar reunião temática da Convenção-Quadro para o controle do tabaco | projetoesperancacooesperanca',
        'arquivo' => 'carta-12.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-14-2018',
        'titulo' => '2018',
        'arquivo' => 'carta-14-2018.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-2',
        'titulo' => '2006',
        'arquivo' => 'carta-2.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-3',
        'titulo' => '2007',
        'arquivo' => 'carta-3.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-4',
        'titulo' => '2008',
        'arquivo' => 'carta-4.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-5',
        'titulo' => '2009',
        'arquivo' => 'carta-5.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-6',
        'titulo' => '2010',
        'arquivo' => 'carta-6.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-7',
        'titulo' => 'Feicoop irá sediar reunião temática da Convenção-Quadro para o controle do tabaco | projetoesperancacooesperanca',
        'arquivo' => 'carta-7.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-8',
        'titulo' => 'Feicoop irá sediar reunião temática da Convenção-Quadro para o controle do tabaco | projetoesperancacooesperanca',
        'arquivo' => 'carta-8.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-9',
        'titulo' => 'Feicoop irá sediar reunião temática da Convenção-Quadro para o controle do tabaco | projetoesperancacooesperanca',
        'arquivo' => 'carta-9.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-da-31',
        'titulo' => 'Carta da 31ª FEICOOP',
        'arquivo' => 'carta-da-31.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'carta-de-agradecimento',
        'titulo' => 'Carta de Agradecimento',
        'arquivo' => 'carta-de-agradecimento.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'cartas-historicas',
        'titulo' => '2005',
        'arquivo' => 'cartas-historicas.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-rede-esperanca',
        'titulo' => 'Cartas da Feicoop',
        'arquivo' => 'copia-rede-esperanca.html',
        'grupo' => 'Cartas das edições',
    ],
    [
        'tipo' => 'page',
        'slug' => 'em-textos',
        'titulo' => 'Em Textos',
        'arquivo' => 'em-textos.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'exto-03',
        'titulo' => 'exto 03',
        'arquivo' => 'exto-03.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'poemas',
        'titulo' => 'Feicoop irá sediar reunião temática da Convenção-Quadro para o controle do tabaco | projetoesperancacooesperanca',
        'arquivo' => 'poemas.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'texto-02',
        'titulo' => 'texto 02',
        'arquivo' => 'texto-02.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'texto-10',
        'titulo' => 'texto 10',
        'arquivo' => 'texto-10.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'texto-4',
        'titulo' => 'texto 4',
        'arquivo' => 'texto-4.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'texto-5',
        'titulo' => 'texto 5',
        'arquivo' => 'texto-5.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'texto-6',
        'titulo' => 'texto 6',
        'arquivo' => 'texto-6.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'texto-7',
        'titulo' => 'texto 7',
        'arquivo' => 'texto-7.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'texto-8',
        'titulo' => 'texto 8',
        'arquivo' => 'texto-8.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'textos-livros-publicacoes',
        'titulo' => 'Textos Livros Publicações',
        'arquivo' => 'textos-livros-publicacoes.html',
        'grupo' => 'Textos e publicações',
    ],
    [
        'tipo' => 'page',
        'slug' => 'cartazes-historicos',
        'titulo' => 'Cartazes Históricos',
        'arquivo' => 'cartazes-historicos.html',
        'grupo' => 'Memória e acervo visual',
    ],
    [
        'tipo' => 'page',
        'slug' => 'dados-finais',
        'titulo' => 'Dados Finais',
        'arquivo' => 'dados-finais.html',
        'grupo' => 'Memória e acervo visual',
    ],
    [
        'tipo' => 'page',
        'slug' => 'datas-historicas',
        'titulo' => 'Datas Históricas',
        'arquivo' => 'datas-historicas.html',
        'grupo' => 'Memória e acervo visual',
    ],
    [
        'tipo' => 'page',
        'slug' => 'fotos',
        'titulo' => 'Fotos',
        'arquivo' => 'fotos.html',
        'grupo' => 'Memória e acervo visual',
    ],
    [
        'tipo' => 'page',
        'slug' => 'fotos-1',
        'titulo' => 'Fotos',
        'arquivo' => 'fotos-1.html',
        'grupo' => 'Memória e acervo visual',
    ],
    [
        'tipo' => 'page',
        'slug' => 'graficos-historicos',
        'titulo' => 'Gráficos Históricos',
        'arquivo' => 'graficos-historicos.html',
        'grupo' => 'Memória e acervo visual',
    ],
    [
        'tipo' => 'page',
        'slug' => 'rede-esperanca',
        'titulo' => 'Vídeos Rede Esperança',
        'arquivo' => 'rede-esperanca.html',
        'grupo' => 'Memória e acervo visual',
    ],
    [
        'tipo' => 'page',
        'slug' => 'videos-historicos',
        'titulo' => 'Vídeos históricos',
        'arquivo' => 'videos-historicos.html',
        'grupo' => 'Memória e acervo visual',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-esperanca-cooesperanca-30-anos',
        'titulo' => 'Esperança/Cooesperança 36 Anos',
        'arquivo' => 'copia-esperanca-cooesperanca-30-anos.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-inicial',
        'titulo' => 'projetoesperancacooesperanca',
        'arquivo' => 'copia-inicial.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-quem-somos',
        'titulo' => 'Quem Somos 34 anos',
        'arquivo' => 'copia-quem-somos.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'copia-rede-esperanca-1',
        'titulo' => 'Rede Esperança',
        'arquivo' => 'copia-rede-esperanca-1.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'especial-30-anos',
        'titulo' => 'Esperança/Cooesperança 30 Anos',
        'arquivo' => 'especial-30-anos.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'historico-o-feirao-colonial',
        'titulo' => 'Histórico O Feirão',
        'arquivo' => 'historico-o-feirao-colonial.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'memorial-dom-ivo',
        'titulo' => 'Memorial Dom Ivo',
        'arquivo' => 'memorial-dom-ivo.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'pontodecultura',
        'titulo' => 'Ponto de Cultura',
        'arquivo' => 'pontodecultura.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'sobre-1',
        'titulo' => 'Sobre 1',
        'arquivo' => 'sobre-1.html',
        'grupo' => 'O Projeto e o Feirão',
    ],
    [
        'tipo' => 'page',
        'slug' => 'feicoop-online-2020',
        'titulo' => 'FEICOOP Online 2020',
        'arquivo' => 'feicoop-online-2020.html',
        'grupo' => 'Eventos online e mostras (2020–2021)',
    ],
    [
        'tipo' => 'page',
        'slug' => 'feira-online-2020',
        'titulo' => 'Feira Online 2020',
        'arquivo' => 'feira-online-2020.html',
        'grupo' => 'Eventos online e mostras (2020–2021)',
    ],
    [
        'tipo' => 'page',
        'slug' => 'feira-virtual-2021',
        'titulo' => 'Feira Virtual',
        'arquivo' => 'feira-virtual-2021.html',
        'grupo' => 'Eventos online e mostras (2020–2021)',
    ],
    [
        'tipo' => 'page',
        'slug' => 'jornada-formativa-2020',
        'titulo' => 'Jornada Formativa',
        'arquivo' => 'jornada-formativa-2020.html',
        'grupo' => 'Eventos online e mostras (2020–2021)',
    ],
    [
        'tipo' => 'page',
        'slug' => 'jornada-formativa-2021',
        'titulo' => 'Jornada Formativa Virtual',
        'arquivo' => 'jornada-formativa-2021.html',
        'grupo' => 'Eventos online e mostras (2020–2021)',
    ],
    [
        'tipo' => 'page',
        'slug' => 'mostra-arte-cultura-2020',
        'titulo' => 'Arte',
        'arquivo' => 'mostra-arte-cultura-2020.html',
        'grupo' => 'Eventos online e mostras (2020–2021)',
    ],
    [
        'tipo' => 'page',
        'slug' => 'mostra-cultural-2021',
        'titulo' => 'Mostra Cultural',
        'arquivo' => 'mostra-cultural-2021.html',
        'grupo' => 'Eventos online e mostras (2020–2021)',
    ],
    [
        'tipo' => 'page',
        'slug' => 'blog-co9e',
        'titulo' => 'Blog',
        'arquivo' => 'blog-co9e.html',
        'grupo' => 'Blog antigo',
    ],
    [
        'tipo' => 'page',
        'slug' => 'blog-co9e-categories-categoria-1',
        'titulo' => 'Categoria 1',
        'arquivo' => 'blog-co9e-categories-categoria-1.html',
        'grupo' => 'Blog antigo',
    ],
    [
        'tipo' => 'page',
        'slug' => 'blog-co9e-categories-categoria-2',
        'titulo' => 'Categoria 2',
        'arquivo' => 'blog-co9e-categories-categoria-2.html',
        'grupo' => 'Blog antigo',
    ],
    [
        'tipo' => 'page',
        'slug' => 'links',
        'titulo' => 'Links',
        'arquivo' => 'links.html',
        'grupo' => 'Diversos',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2013-05-01-uma-acao-arbitraria-na-vespera-de-natal',
        'titulo' => 'UMA AÇÃO ARBITRÁRIA NA VÉSPERA DE NATAL',
        'arquivo' => 'single-post-2013-05-01-uma-acao-arbitraria-na-vespera-de-natal.html',
        'data' => '2013-05-01',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2014-12-01-papa-francisco-recebe-kit-com-materiais-sobre-economia-solidaria',
        'titulo' => 'Papa Francisco recebe kit com materiais sobre Economia Solidária',
        'arquivo' => 'single-post-2014-12-01-papa-francisco-recebe-kit-com-materiais-sobre-economia-solidaria.html',
        'data' => '2014-12-01',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-01-01-boas-festas-feliz-e-abencoado-2015',
        'titulo' => 'BOAS FESTAS! FELIZ E ABENÇOADO 2015!',
        'arquivo' => 'single-post-2015-01-01-boas-festas-feliz-e-abencoado-2015.html',
        'data' => '2015-01-01',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-01-16-o-projeto-esperancacooesperanca-participa-dos-eventos-internacionais-uruguay',
        'titulo' => 'O PROJETO ESPERANÇA/COOESPERANÇA PARTICIPA DOS EVENTOS INTERNACIONAIS – URUGUAY',
        'arquivo' => 'single-post-2015-01-16-o-projeto-esperancacooesperanca-participa-dos-eventos-internacionais-uruguay.html',
        'data' => '2015-01-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-02-16-38a-romaria-da-terra',
        'titulo' => '38ª ROMARIA DA TERRA',
        'arquivo' => 'single-post-2015-02-16-38a-romaria-da-terra.html',
        'data' => '2015-02-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-02-16-campanha-fraternidade-2015-igreja-e-sociedade',
        'titulo' => 'CAMPANHA FRATERNIDADE 2015 – IGREJA E SOCIEDADE',
        'arquivo' => 'single-post-2015-02-16-campanha-fraternidade-2015-igreja-e-sociedade.html',
        'data' => '2015-02-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-03-02-dom-jose-ivo-lorscheiter-bispo-de-santa-maria-rs',
        'titulo' => 'DOM JOSE IVO LORSCHEITER, bispo de Santa Maria, RS.',
        'arquivo' => 'single-post-2015-03-02-dom-jose-ivo-lorscheiter-bispo-de-santa-maria-rs.html',
        'data' => '2015-03-02',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-03-02-memoria-agradecida-oito-anos-da-passagem-de-dom-ivo',
        'titulo' => 'MEMÓRIA AGRADECIDA: Oito Anos da Passagem de Dom Ivo',
        'arquivo' => 'single-post-2015-03-02-memoria-agradecida-oito-anos-da-passagem-de-dom-ivo.html',
        'data' => '2015-03-02',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-03-04-centro-de-referencia-em-economia-solidaria-ira-receber-nova-ampliacao',
        'titulo' => 'Centro de Referência em Economia Solidária irá receber nova ampliação',
        'arquivo' => 'single-post-2015-03-04-centro-de-referencia-em-economia-solidaria-ira-receber-nova-ampliacao.html',
        'data' => '2015-03-04',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-03-20-convite-audiencia-publica',
        'titulo' => 'Convite Audiência Pública',
        'arquivo' => 'single-post-2015-03-20-convite-audiencia-publica.html',
        'data' => '2015-03-20',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-03-20-dia-do-acolhimento',
        'titulo' => 'Dia do Acolhimento',
        'arquivo' => 'single-post-2015-03-20-dia-do-acolhimento.html',
        'data' => '2015-03-20',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-03-21-22-de-marco-dia-mundial-da-agua',
        'titulo' => '22 de março! DIA MUNDIAL DA ÁGUA',
        'arquivo' => 'single-post-2015-03-21-22-de-marco-dia-mundial-da-agua.html',
        'data' => '2015-03-21',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-03-23-audiencia-publica-expoe-problemas-da-implantacao-do-susaf',
        'titulo' => 'Audiência pública expõe problemas da implantação do Susaf',
        'arquivo' => 'single-post-2015-03-23-audiencia-publica-expoe-problemas-da-implantacao-do-susaf.html',
        'data' => '2015-03-23',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-03-23-pequenos-agricultores-ganham-apoio-em-audiencia',
        'titulo' => 'Pequenos agricultores ganham apoio em audiência',
        'arquivo' => 'single-post-2015-03-23-pequenos-agricultores-ganham-apoio-em-audiencia.html',
        'data' => '2015-03-23',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-04-30-carta-aberta-a-comunidade-santamariense',
        'titulo' => 'CARTA ABERTA À COMUNIDADE SANTAMARIENSE',
        'arquivo' => 'single-post-2015-04-30-carta-aberta-a-comunidade-santamariense.html',
        'data' => '2015-04-30',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-04-30-carta-e-formulario-reforma-politica',
        'titulo' => 'Carta e Formulário Reforma Politica',
        'arquivo' => 'single-post-2015-04-30-carta-e-formulario-reforma-politica.html',
        'data' => '2015-04-30',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-05-04-1a-feira-da-biodiversidade',
        'titulo' => '1ª FEIRA DA BIODIVERSIDADE',
        'arquivo' => 'single-post-2015-05-04-1a-feira-da-biodiversidade.html',
        'data' => '2015-05-04',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-05-04-reforma-politica-democratica-e-eleicoes-limpas-prorrogado-o-prazo-para-entrega-das-assina',
        'titulo' => 'Reforma Política Democrática e Eleições Limpas: prorrogado o prazo para entrega das assinaturas',
        'arquivo' => 'single-post-2015-05-04-reforma-politica-democratica-e-eleicoes-limpas-prorrogado-o-prazo-para-entrega-das-assina.html',
        'data' => '2015-05-04',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-05-06-feliz-dias-das-maes',
        'titulo' => 'FELIZ DIAS DAS MÃES',
        'arquivo' => 'single-post-2015-05-06-feliz-dias-das-maes.html',
        'data' => '2015-05-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-05-06-solidariedade-ao-nepal-socorro-as-familias-vitimas-do-terremoto',
        'titulo' => 'SOLIDARIEDADE AO NEPAL 
SOCORRO AS FAMILIAS VÍTIMAS DO TERREMOTO',
        'arquivo' => 'single-post-2015-05-06-solidariedade-ao-nepal-socorro-as-familias-vitimas-do-terremoto.html',
        'data' => '2015-05-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-05-07-audiencia-publica-do-susafrs',
        'titulo' => 'Audiência Pública do SUSAF-RS',
        'arquivo' => 'single-post-2015-05-07-audiencia-publica-do-susafrs.html',
        'data' => '2015-05-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-05-20-22a-feicoop-e-lancada-na-1a-feira-da-biodiversidade',
        'titulo' => '22ª Feicoop é lançada na 1ª Feira da Biodiversidade',
        'arquivo' => 'single-post-2015-05-20-22a-feicoop-e-lancada-na-1a-feira-da-biodiversidade.html',
        'data' => '2015-05-20',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-05-20-feirao-colonial-23-anos-de-historia',
        'titulo' => 'FEIRÃO COLONIAL: 23 ANOS DE HISTÓRIA',
        'arquivo' => 'single-post-2015-05-20-feirao-colonial-23-anos-de-historia.html',
        'data' => '2015-05-20',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-05-25-intercambio-do-brasil-e-italia-nas-experiencias-mundiais-do-comercio-justo',
        'titulo' => 'INTERCÂMBIO DO BRASIL E ITÁLIA NAS EXPERIÊNCIAS MUNDIAIS
DO COMÉRCIO JUSTO.',
        'arquivo' => 'single-post-2015-05-25-intercambio-do-brasil-e-italia-nas-experiencias-mundiais-do-comercio-justo.html',
        'data' => '2015-05-25',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-06-09-jornal-aldeia',
        'titulo' => 'Jornal Aldeia',
        'arquivo' => 'single-post-2015-06-09-jornal-aldeia.html',
        'data' => '2015-06-09',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-06-09-somosmuitos',
        'titulo' => '#SomosMuitos',
        'arquivo' => 'single-post-2015-06-09-somosmuitos.html',
        'data' => '2015-06-09',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-06-24-convite-para-a-plenaria-geral-em-preparacao-aos-eventos-internacionais-do-cooperativismo',
        'titulo' => 'CONVITE PARA A PLENÁRIA GERAL EM PREPARAÇÃO AOS
EVENTOS INTERNACIONAIS DO COOPERATIVISMO E
DA ECONOM',
        'arquivo' => 'single-post-2015-06-24-convite-para-a-plenaria-geral-em-preparacao-aos-eventos-internacionais-do-cooperativismo.html',
        'data' => '2015-06-24',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-06-30-feicoop-2015',
        'titulo' => 'FEICOOP 2015',
        'arquivo' => 'single-post-2015-06-30-feicoop-2015.html',
        'data' => '2015-06-30',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-06-30-montagem-da-22a-feicoop-inicia-esta-semana',
        'titulo' => 'Montagem da 22ª Feicoop inicia esta semana',
        'arquivo' => 'single-post-2015-06-30-montagem-da-22a-feicoop-inicia-esta-semana.html',
        'data' => '2015-06-30',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-07-programacao-final-22a-feicoop',
        'titulo' => 'PROGRAMAÇÃO FINAL 22ª FEICOOP',
        'arquivo' => 'single-post-2015-07-07-programacao-final-22a-feicoop.html',
        'data' => '2015-07-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-09-desmanche-do-quadro-da-senaes-preocupa-forum-brasileiro-de-economia-solidaria',
        'titulo' => 'Desmanche do quadro da Senaes preocupa Fórum Brasileiro de Economia Solidária',
        'arquivo' => 'single-post-2015-07-09-desmanche-do-quadro-da-senaes-preocupa-forum-brasileiro-de-economia-solidaria.html',
        'data' => '2015-07-09',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-10-a-senaes-nao-e-do-governo-e-nao-e-do-pdt-a-senaes-e-nossa-afirma-irma-lourdes-dill',
        'titulo' => '"A Senaes não é do governo e não é do PDT, a Senaes é nossa", afirma irmã Lourdes Dill',
        'arquivo' => 'single-post-2015-07-10-a-senaes-nao-e-do-governo-e-nao-e-do-pdt-a-senaes-e-nossa-afirma-irma-lourdes-dill.html',
        'data' => '2015-07-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-10-uma-feira-multicultural',
        'titulo' => 'Uma feira multicultural',
        'arquivo' => 'single-post-2015-07-10-uma-feira-multicultural.html',
        'data' => '2015-07-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-11-abertura-da-feicoop-e-marcada-por-discursos-em-defesa-da-senaes',
        'titulo' => 'Abertura da Feicoop é marcada por discursos em defesa da Senaes',
        'arquivo' => 'single-post-2015-07-11-abertura-da-feicoop-e-marcada-por-discursos-em-defesa-da-senaes.html',
        'data' => '2015-07-11',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-11-feicoop-inicia-com-seminarios-lotados',
        'titulo' => 'Feicoop inicia com seminários lotados',
        'arquivo' => 'single-post-2015-07-11-feicoop-inicia-com-seminarios-lotados.html',
        'data' => '2015-07-11',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-12-a-tecnologia-chegou-a-feicoop',
        'titulo' => 'A tecnologia chegou à Feicoop',
        'arquivo' => 'single-post-2015-07-12-a-tecnologia-chegou-a-feicoop.html',
        'data' => '2015-07-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-12-projeto-de-lei-que-retira-simbolo-t-de-produtos-transgenicos-e-repudiado-em-seminario-da',
        'titulo' => 'Projeto de Lei que retira símbolo "T" de produtos transgênicos é repudiado em seminário da',
        'arquivo' => 'single-post-2015-07-12-projeto-de-lei-que-retira-simbolo-t-de-produtos-transgenicos-e-repudiado-em-seminario-da.html',
        'data' => '2015-07-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-12-premio-bndes-de-boas-praticas-em-economia-solidaria-entrega-r-126-milhao-na-feicoop',
        'titulo' => 'Prêmio BNDES de Boas Práticas em Economia Solidária entrega R$ 1,26 milhão na Feicoop',
        'arquivo' => 'single-post-2015-07-12-premio-bndes-de-boas-praticas-em-economia-solidaria-entrega-r-126-milhao-na-feicoop.html',
        'data' => '2015-07-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-13-feicoop-supera-expectativas-e-bate-recorde-de-publico',
        'titulo' => 'Feicoop supera expectativas e bate recorde de público',
        'arquivo' => 'single-post-2015-07-13-feicoop-supera-expectativas-e-bate-recorde-de-publico.html',
        'data' => '2015-07-13',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-13-projeto-esperancacooesperanca-ja-planeja-a-feira-de-2016',
        'titulo' => 'Projeto Esperança/Cooesperança já planeja a Feira de 2016',
        'arquivo' => 'single-post-2015-07-13-projeto-esperancacooesperanca-ja-planeja-a-feira-de-2016.html',
        'data' => '2015-07-13',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-07-13-ultima-chance-para-visitar-a-22a-feicoop',
        'titulo' => 'Última chance para visitar a 22ª Feicoop',
        'arquivo' => 'single-post-2015-07-13-ultima-chance-para-visitar-a-22a-feicoop.html',
        'data' => '2015-07-13',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-08-07-25o-seminario-de-alternativas-a-cultura-do-fumo',
        'titulo' => '25º SEMINÁRIO DE ALTERNATIVAS À CULTURA DO FUMO',
        'arquivo' => 'single-post-2015-08-07-25o-seminario-de-alternativas-a-cultura-do-fumo.html',
        'data' => '2015-08-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-08-10-seminario-estadual-ira-discutir-alternativas-a-cultura-do-fumo',
        'titulo' => 'Seminário Estadual irá discutir alternativas à cultura do fumo',
        'arquivo' => 'single-post-2015-08-10-seminario-estadual-ira-discutir-alternativas-a-cultura-do-fumo.html',
        'data' => '2015-08-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-08-12-rede-comsol-divulga-relatorio-do-intercambio-internacional-na-italia',
        'titulo' => 'Rede ComSol Divulga Relatório do Intercâmbio Internacional na Itália',
        'arquivo' => 'single-post-2015-08-12-rede-comsol-divulga-relatorio-do-intercambio-internacional-na-italia.html',
        'data' => '2015-08-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-08-14-iv-congresso-nacional-da-cpt',
        'titulo' => 'IV CONGRESSO NACIONAL DA CPT',
        'arquivo' => 'single-post-2015-08-14-iv-congresso-nacional-da-cpt.html',
        'data' => '2015-08-14',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-08-26-campanha-10-milhoes-de-estrelas',
        'titulo' => 'CAMPANHA 10 MILHÕES DE ESTRELAS',
        'arquivo' => 'single-post-2015-08-26-campanha-10-milhoes-de-estrelas.html',
        'data' => '2015-08-26',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-08-26-caritas-regional-rs-lanca-campanha-de-solidariedade-para-apoiar-gauchos-atingidos-pelas-e',
        'titulo' => 'Cáritas Regional RS lança campanha de solidariedade para apoiar gaúchos atingidos pelas emergências',
        'arquivo' => 'single-post-2015-08-26-caritas-regional-rs-lanca-campanha-de-solidariedade-para-apoiar-gauchos-atingidos-pelas-e.html',
        'data' => '2015-08-26',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-09-04-40a-feira-na-primavera-ocorre-sabado-no-centro-de-referencia-em-economia-solidaria',
        'titulo' => '40ª Feira na Primavera ocorre sábado no Centro de Referência em Economia Solidária',
        'arquivo' => 'single-post-2015-09-04-40a-feira-na-primavera-ocorre-sabado-no-centro-de-referencia-em-economia-solidaria.html',
        'data' => '2015-09-04',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-09-11-trote-solidario',
        'titulo' => 'TROTE SOLIDÁRIO',
        'arquivo' => 'single-post-2015-09-11-trote-solidario.html',
        'data' => '2015-09-11',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-10-06-graficos-mostram-de-onde-vem-e-para-onde-vai-a-comida-do-mundo',
        'titulo' => 'Gráficos mostram de onde vem e para onde vai a comida do mundo',
        'arquivo' => 'single-post-2015-10-06-graficos-mostram-de-onde-vem-e-para-onde-vai-a-comida-do-mundo.html',
        'data' => '2015-10-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-10-06-para-acabar-com-a-fome-e-proteger-o-planeta',
        'titulo' => 'Para acabar com a fome e proteger o planeta',
        'arquivo' => 'single-post-2015-10-06-para-acabar-com-a-fome-e-proteger-o-planeta.html',
        'data' => '2015-10-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-10-08-bencao-do-papa-francisco',
        'titulo' => 'BÊNÇÃO DO PAPA FRANCISCO',
        'arquivo' => 'single-post-2015-10-08-bencao-do-papa-francisco.html',
        'data' => '2015-10-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-10-20-seminario-de-estudos-da-enciclica-do-papa-francisco',
        'titulo' => 'SEMINÁRIO DE ESTUDOS DA ENCÍCLICA
DO PAPA FRANCISCO',
        'arquivo' => 'single-post-2015-10-20-seminario-de-estudos-da-enciclica-do-papa-francisco.html',
        'data' => '2015-10-20',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-11-16-milhoes-de-estrelas',
        'titulo' => 'Milhões de Estrelas',
        'arquivo' => 'single-post-2015-11-16-milhoes-de-estrelas.html',
        'data' => '2015-11-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-11-18-caritas-brasileira-inicia-sua-xx-assembleia-nacional',
        'titulo' => 'Cáritas Brasileira inicia sua XX Assembleia Nacional',
        'arquivo' => 'single-post-2015-11-18-caritas-brasileira-inicia-sua-xx-assembleia-nacional.html',
        'data' => '2015-11-18',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2015-11-18-caritas-um-organismo-da-igreja-catolica',
        'titulo' => 'CÁRITAS: UM ORGANISMO DA IGREJA CATÓLICA',
        'arquivo' => 'single-post-2015-11-18-caritas-um-organismo-da-igreja-catolica.html',
        'data' => '2015-11-18',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-1-22-economia-solidaria-outra-economia-acontece',
        'titulo' => '“ECONOMIA  SOLIDÁRIA -  OUTRA  ECONOMIA  ACONTECE”',
        'arquivo' => 'single-post-2016-1-22-economia-solidaria-outra-economia-acontece.html',
        'data' => '2016-01-22',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-1-22-23a-feicoop',
        'titulo' => '23ª FEICOOP',
        'arquivo' => 'single-post-2016-1-22-23a-feicoop.html',
        'data' => '2016-01-22',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-1-22-dona-olivia-moraes',
        'titulo' => 'DONA OLÍVIA MORAES',
        'arquivo' => 'single-post-2016-1-22-dona-olivia-moraes.html',
        'data' => '2016-01-22',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-1-23-39a-romaria-da-terra',
        'titulo' => '39ª ROMARIA DA TERRA',
        'arquivo' => 'single-post-2016-1-23-39a-romaria-da-terra.html',
        'data' => '2016-01-23',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-02-18-39a-romaria-da-terra',
        'titulo' => '39ª  ROMARIA  DA  TERRA',
        'arquivo' => 'single-post-2016-02-18-39a-romaria-da-terra.html',
        'data' => '2016-02-18',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-02-26-conferencia-dos-direitos-humanos-modalidade-livre',
        'titulo' => 'CONFERÊNCIA  DOS  DIREITOS  HUMANOS - (MODALIDADE  LIVRE)',
        'arquivo' => 'single-post-2016-02-26-conferencia-dos-direitos-humanos-modalidade-livre.html',
        'data' => '2016-02-26',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-02-26-conferencia-regional-dos-direitos-humanos-ocorre-sabado-em-santa-maria',
        'titulo' => 'Conferência Regional dos Direitos Humanos ocorre sábado em Santa Maria',
        'arquivo' => 'single-post-2016-02-26-conferencia-regional-dos-direitos-humanos-ocorre-sabado-em-santa-maria.html',
        'data' => '2016-02-26',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-03-23-feliz-pascoa',
        'titulo' => 'Feliz Páscoa',
        'arquivo' => 'single-post-2016-03-23-feliz-pascoa.html',
        'data' => '2016-03-23',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-03-24-carta-aberta-xiii-encontro-nacional-do-forum-brasileiro-de-economia-solidaria',
        'titulo' => 'CARTA ABERTA
 XIII Encontro Nacional do Fórum Brasileiro de Economia Solidária',
        'arquivo' => 'single-post-2016-03-24-carta-aberta-xiii-encontro-nacional-do-forum-brasileiro-de-economia-solidaria.html',
        'data' => '2016-03-24',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-03-29-ato-religiosos-e-religiosas-pela-democracia',
        'titulo' => 'Ato Religiosos e Religiosas pela Democracia',
        'arquivo' => 'single-post-2016-03-29-ato-religiosos-e-religiosas-pela-democracia.html',
        'data' => '2016-03-29',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-04-01-trote-solidario-dos-cursos-de-medicina-da-ufsm-e-unifra',
        'titulo' => 'TROTE SOLIDÁRIO DOS CURSOS DE MEDICINA DA UFSM E UNIFRA',
        'arquivo' => 'single-post-2016-04-01-trote-solidario-dos-cursos-de-medicina-da-ufsm-e-unifra.html',
        'data' => '2016-04-01',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-04-18-campanha-do-brasil-para-santa-maria',
        'titulo' => 'CAMPANHA DO BRASIL PARA SANTA MARIA',
        'arquivo' => 'single-post-2016-04-18-campanha-do-brasil-para-santa-maria.html',
        'data' => '2016-04-18',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-05-10-irma-lourdes-dill-recebe-titulo-de-honra-ao-merito-em-santa-maria',
        'titulo' => 'Irmã Lourdes Dill recebe título de Honra ao Mérito em Santa Maria',
        'arquivo' => 'single-post-2016-05-10-irma-lourdes-dill-recebe-titulo-de-honra-ao-merito-em-santa-maria.html',
        'data' => '2016-05-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-04-produtores-rurais-e-artesaos-projetam-boas-vendas-na-23a-feicoop',
        'titulo' => 'Produtores rurais e artesãos projetam boas vendas na 23ª Feicoop',
        'arquivo' => 'single-post-2016-07-04-produtores-rurais-e-artesaos-projetam-boas-vendas-na-23a-feicoop.html',
        'data' => '2016-07-04',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-04-release-ja-estamos-no-clima-da-feicoop-afirma-irma-lourdes-dill',
        'titulo' => 'Release - “Já estamos no clima da Feicoop”, afirma irmã Lourdes Dill',
        'arquivo' => 'single-post-2016-07-04-release-ja-estamos-no-clima-da-feicoop-afirma-irma-lourdes-dill.html',
        'data' => '2016-07-04',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-05-campanha-nacional-contribui-para-a-realizacao-da-23a-feicoop',
        'titulo' => 'Campanha nacional contribui para a realização da 23ª Feicoop',
        'arquivo' => 'single-post-2016-07-05-campanha-nacional-contribui-para-a-realizacao-da-23a-feicoop.html',
        'data' => '2016-07-05',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-05-convocatoria-para-assembleia-popular-do-movimento-de-economia-solidaria',
        'titulo' => 'Convocatória para Assembleia Popular do Movimento de Economia Solidária',
        'arquivo' => 'single-post-2016-07-05-convocatoria-para-assembleia-popular-do-movimento-de-economia-solidaria.html',
        'data' => '2016-07-05',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-05-programacao-dos-eventos-internacionais-de-economia-solidaria-cooperativismo-e-agricultura',
        'titulo' => 'PROGRAMAÇÃO DOS EVENTOS INTERNACIONAIS DE
ECONOMIA SOLIDÁRIA, COOPERATIVISMO E AGRICULTURA FAMILIAR',
        'arquivo' => 'single-post-2016-07-05-programacao-dos-eventos-internacionais-de-economia-solidaria-cooperativismo-e-agricultura.html',
        'data' => '2016-07-05',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-15-carta-de-agradecimento',
        'titulo' => 'CARTA  DE  AGRADECIMENTO',
        'arquivo' => 'single-post-2016-07-15-carta-de-agradecimento.html',
        'data' => '2016-07-15',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-15-carta-final-da-23a-feicoop',
        'titulo' => 'CARTA FINAL DA 23ª FEICOOP',
        'arquivo' => 'single-post-2016-07-15-carta-final-da-23a-feicoop.html',
        'data' => '2016-07-15',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-15-dados-numericos-dos-eventos-internacionais-2016-santa-maria-rs-brasil',
        'titulo' => 'DADOS NÚMERICOS DOS EVENTOS INTERNACIONAIS – 2016
SANTA MARIA – RS – BRASIL',
        'arquivo' => 'single-post-2016-07-15-dados-numericos-dos-eventos-internacionais-2016-santa-maria-rs-brasil.html',
        'data' => '2016-07-15',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-15-materiais-na-imprensa-divulgacao-da-23a-feicoop-e-a-12a-feira-latino-americana-de-ecoso',
        'titulo' => 'MATERIAIS NA IMPRENSA – DIVULGAÇÃO da
23ª FEICOOP e a 12ª Feira Latino Americana de Ecosol',
        'arquivo' => 'single-post-2016-07-15-materiais-na-imprensa-divulgacao-da-23a-feicoop-e-a-12a-feira-latino-americana-de-ecoso.html',
        'data' => '2016-07-15',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-07-29-inicia-a-montagem-da-infraestrutura-da-24a-feicoop',
        'titulo' => 'Inicia a montagem da infraestrutura da 24ª Feicoop',
        'arquivo' => 'single-post-2016-07-29-inicia-a-montagem-da-infraestrutura-da-24a-feicoop.html',
        'data' => '2016-07-29',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-09-08-41a-feira-da-primavera',
        'titulo' => '41ª Feira da Primavera',
        'arquivo' => 'single-post-2016-09-08-41a-feira-da-primavera.html',
        'data' => '2016-09-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-10-07-audiencia-publica-sobre-ecosol-reune-mais-de-300-pessoas',
        'titulo' => 'Audiência pública sobre EcoSol reúne mais de 300 pessoas',
        'arquivo' => 'single-post-2016-10-07-audiencia-publica-sobre-ecosol-reune-mais-de-300-pessoas.html',
        'data' => '2016-10-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-10-10-circular-sem-terrinha',
        'titulo' => 'Encontro Estadual Sem Terrinha',
        'arquivo' => 'single-post-2016-10-10-circular-sem-terrinha.html',
        'data' => '2016-10-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-10-13-caritas-brasileira-se-solidariza-com-vitimas-do-furacao-no-haiti',
        'titulo' => 'Cáritas Brasileira se solidariza com vítimas do furacão no Haiti',
        'arquivo' => 'single-post-2016-10-13-caritas-brasileira-se-solidariza-com-vitimas-do-furacao-no-haiti.html',
        'data' => '2016-10-13',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-11-08-60-anos-da-caritas-brasileira-e-a-campanha-10-milhoes-de-estrelas',
        'titulo' => '60 anos da Cáritas Brasileira e a Campanha “10 Milhões de Estrelas”!',
        'arquivo' => 'single-post-2016-11-08-60-anos-da-caritas-brasileira-e-a-campanha-10-milhoes-de-estrelas.html',
        'data' => '2016-11-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-11-08-caritas-brasileira-60-anos',
        'titulo' => 'CÁRITAS BRASILEIRA: 60 ANOS',
        'arquivo' => 'single-post-2016-11-08-caritas-brasileira-60-anos.html',
        'data' => '2016-11-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-11-08-encontro-dos-sem-terrinha',
        'titulo' => 'O Encontro dos Sem Terrinha aconteceu em Santa Maria',
        'arquivo' => 'single-post-2016-11-08-encontro-dos-sem-terrinha.html',
        'data' => '2016-11-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-11-08-projeto-esperancacooesperanca',
        'titulo' => 'PROJETO ESPERANÇA/COOESPERANÇA',
        'arquivo' => 'single-post-2016-11-08-projeto-esperancacooesperanca.html',
        'data' => '2016-11-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-11-18-caritas-brasileira-60-anos',
        'titulo' => 'CÁRITAS BRASILEIRA: 60 ANOS',
        'arquivo' => 'single-post-2016-11-18-caritas-brasileira-60-anos.html',
        'data' => '2016-11-18',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-11-22-feirao-colonial',
        'titulo' => 'FEIRÃO COLONIAL',
        'arquivo' => 'single-post-2016-11-22-feirao-colonial.html',
        'data' => '2016-11-22',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-11-23-livro-modelo-de-gestao-de-um-empreendimento-de-economia-solidaria-o-projeto-esperancacooe',
        'titulo' => 'Livro: Modelo de Gestão de um Empreendimento de Economia Solidária o Projeto Esperança/Cooesperança',
        'arquivo' => 'single-post-2016-11-23-livro-modelo-de-gestao-de-um-empreendimento-de-economia-solidaria-o-projeto-esperancacooe.html',
        'data' => '2016-11-23',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2016-12-06-feliz-natal',
        'titulo' => 'Feliz Natal',
        'arquivo' => 'single-post-2016-12-06-feliz-natal.html',
        'data' => '2016-12-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-01-02-gratidao-por-2016',
        'titulo' => 'Gratidão por  2016',
        'arquivo' => 'single-post-2017-01-02-gratidao-por-2016.html',
        'data' => '2017-01-02',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-01-20-40o-edicao-da-romaria-da-terra',
        'titulo' => '40º edição da Romaria da Terra',
        'arquivo' => 'single-post-2017-01-20-40o-edicao-da-romaria-da-terra.html',
        'data' => '2017-01-20',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-06-10-anos-da-passagem-de-dom-ivo',
        'titulo' => '10 ANOS DA PASSAGEM DE DOM IVO!',
        'arquivo' => 'single-post-2017-03-06-10-anos-da-passagem-de-dom-ivo.html',
        'data' => '2017-03-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-06-a-palavra-do-pastor-dom-ivo-10-anos-no-ceu-helio-adelar-rubert-04032017',
        'titulo' => 'A Palavra do Pastor: DOM IVO 10 ANOS NO CÉU
+ Hélio Adelar Rubert – 04/03/2017',
        'arquivo' => 'single-post-2017-03-06-a-palavra-do-pastor-dom-ivo-10-anos-no-ceu-helio-adelar-rubert-04032017.html',
        'data' => '2017-03-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-06-dom-jose-ivo-lorscheiter-bispo-de-st-mariars',
        'titulo' => 'DOM JOSE IVO LORSCHEITER, Bispo de St. Maria/RS.',
        'arquivo' => 'single-post-2017-03-06-dom-jose-ivo-lorscheiter-bispo-de-st-mariars.html',
        'data' => '2017-03-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-06-ha-30-anos-atras',
        'titulo' => 'HÁ 30 ANOS ATRÁS...',
        'arquivo' => 'single-post-2017-03-06-ha-30-anos-atras.html',
        'data' => '2017-03-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-06-mulheres-e-homens-vamos-a-luta-pelo-fim-da-violencia-contra-as-mulheres-nenhum-direito-a',
        'titulo' => 'Mulheres e homens.
Vamos à luta! Pelo Fim da Violência contra as Mulheres. Nenhum direito a menos!',
        'arquivo' => 'single-post-2017-03-06-mulheres-e-homens-vamos-a-luta-pelo-fim-da-violencia-contra-as-mulheres-nenhum-direito-a.html',
        'data' => '2017-03-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-06-projeto-esperancacooesperanca-e-prefeitura-de-santa-maria-iniciam-o-planejamento-da-24a-f',
        'titulo' => 'Projeto Esperança/Cooesperança e Prefeitura de Santa Maria iniciam o planejamento da 24ª Feicoop',
        'arquivo' => 'single-post-2017-03-06-projeto-esperancacooesperanca-e-prefeitura-de-santa-maria-iniciam-o-planejamento-da-24a-f.html',
        'data' => '2017-03-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-16-previdencia-reformar-para-excluir',
        'titulo' => 'Previdência: reformar para excluir?',
        'arquivo' => 'single-post-2017-03-16-previdencia-reformar-para-excluir.html',
        'data' => '2017-03-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-30-24a-feicoop-sera-lancada-sabado-1o',
        'titulo' => '24ª Feicoop será lançada sábado (1º)',
        'arquivo' => 'single-post-2017-03-30-24a-feicoop-sera-lancada-sabado-1o.html',
        'data' => '2017-03-30',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-03-30-chegadeagrotoxico',
        'titulo' => '#ChegaDeAgrotóxico',
        'arquivo' => 'single-post-2017-03-30-chegadeagrotoxico.html',
        'data' => '2017-03-30',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-04-06-feira-mostra-sul',
        'titulo' => 'single-post/2017/04/06/feira-mostra-sul',
        'arquivo' => 'single-post-2017-04-06-feira-mostra-sul.html',
        'data' => '2017-04-06',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-04-12-impactos-da-economia-solidaria-em-santa-maria-sao-avaliados-por-representantes-da-misereo',
        'titulo' => 'Impactos da Economia Solidária em Santa Maria são avaliados por representantes da Misereor',
        'arquivo' => 'single-post-2017-04-12-impactos-da-economia-solidaria-em-santa-maria-sao-avaliados-por-representantes-da-misereo.html',
        'data' => '2017-04-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-04-17-feira-dos-fabricantes',
        'titulo' => 'Feira dos Fabricantes',
        'arquivo' => 'single-post-2017-04-17-feira-dos-fabricantes.html',
        'data' => '2017-04-17',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-04-28-10o-exposicao-regional-de-orquideas',
        'titulo' => '10º Exposição Regional de Orquídeas',
        'arquivo' => 'single-post-2017-04-28-10o-exposicao-regional-de-orquideas.html',
        'data' => '2017-04-28',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-04-28-a-caritas-brasileira-adere-a-greve-geral',
        'titulo' => 'A Cáritas Brasileira adere à GREVE GERAL',
        'arquivo' => 'single-post-2017-04-28-a-caritas-brasileira-adere-a-greve-geral.html',
        'data' => '2017-04-28',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-06-07-falta-um-mes-para-o-inicio-da-24a-feicoop',
        'titulo' => 'Falta um mês para o início da 24ª Feicoop',
        'arquivo' => 'single-post-2017-06-07-falta-um-mes-para-o-inicio-da-24a-feicoop.html',
        'data' => '2017-06-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-06-24-plenaria-geral-marca-a-reta-final-de-preparacao-para-a-24a-feicoop',
        'titulo' => 'Plenária Geral marca a reta final de preparação para a 24ª Feicoop',
        'arquivo' => 'single-post-2017-06-24-plenaria-geral-marca-a-reta-final-de-preparacao-para-a-24a-feicoop.html',
        'data' => '2017-06-24',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-01-produtos-de-origem-animal-de-todo-o-rio-grande-do-sul-oriundos-do-sim-poderao-ser-vendido',
        'titulo' => 'Produtos de origem animal de todo o Rio Grande do Sul, oriundos do SIM, poderão ser vendidos na Feic',
        'arquivo' => 'single-post-2017-07-01-produtos-de-origem-animal-de-todo-o-rio-grande-do-sul-oriundos-do-sim-poderao-ser-vendido.html',
        'data' => '2017-07-01',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-01-projeto-catando-cidadania-realiza-encerramento-do-semestre',
        'titulo' => 'Projeto Catando Cidadania realiza encerramento do semestre',
        'arquivo' => 'single-post-2017-07-01-projeto-catando-cidadania-realiza-encerramento-do-semestre.html',
        'data' => '2017-07-01',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-04-pavilhoes-ja-estao-prontos-para-receber-os-expositores-da-24a-feicoop',
        'titulo' => 'Pavilhões já estão prontos para receber os expositores da 24ª Feicoop',
        'arquivo' => 'single-post-2017-07-04-pavilhoes-ja-estao-prontos-para-receber-os-expositores-da-24a-feicoop.html',
        'data' => '2017-07-04',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-05-confira-a-programacao-da-24a-feicoop',
        'titulo' => 'Confira a programação da 24ª Feicoop',
        'arquivo' => 'single-post-2017-07-05-confira-a-programacao-da-24a-feicoop.html',
        'data' => '2017-07-05',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-05-ja-tem-expositor-montando-seu-espaco-na-24a-feicoop',
        'titulo' => 'Já tem expositor montando seu espaço na 24ª Feicoop',
        'arquivo' => 'single-post-2017-07-05-ja-tem-expositor-montando-seu-espaco-na-24a-feicoop.html',
        'data' => '2017-07-05',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-07-24a-feicoop-e-marcada-por-coragem-fe-e-teimosia-profetica',
        'titulo' => '24ª Feicoop é marcada por coragem, fé e teimosia profética',
        'arquivo' => 'single-post-2017-07-07-24a-feicoop-e-marcada-por-coragem-fe-e-teimosia-profetica.html',
        'data' => '2017-07-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-07-continuidade-da-rede-comsol-e-discutida-em-santa-maria',
        'titulo' => 'Continuidade da Rede ComSol é discutida em Santa Maria',
        'arquivo' => 'single-post-2017-07-07-continuidade-da-rede-comsol-e-discutida-em-santa-maria.html',
        'data' => '2017-07-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-07-mapeamento-dos-fundos-rotativos-solidarios-serao-concluidos-ate-o-final-do-mes',
        'titulo' => 'Mapeamento dos Fundos Rotativos Solidários serão concluídos até o final do mês',
        'arquivo' => 'single-post-2017-07-07-mapeamento-dos-fundos-rotativos-solidarios-serao-concluidos-ate-o-final-do-mes.html',
        'data' => '2017-07-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-07-uruguaios-chegam-motivados-a-feicoop',
        'titulo' => 'Uruguaios chegam motivados à Feicoop',
        'arquivo' => 'single-post-2017-07-07-uruguaios-chegam-motivados-a-feicoop.html',
        'data' => '2017-07-07',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-08-audiencia-publica-resulta-na-criacao-de-grupo-de-trabalho-que-ira-tratar-da-situacao-dos',
        'titulo' => 'Audiência pública resulta na criação de grupo de trabalho que irá tratar da situação dos catadores',
        'arquivo' => 'single-post-2017-07-08-audiencia-publica-resulta-na-criacao-de-grupo-de-trabalho-que-ira-tratar-da-situacao-dos.html',
        'data' => '2017-07-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-08-em-caminhada-publico-da-feicoop-pede-diretas-ja-e-saida-de-michel-temer',
        'titulo' => 'Em caminhada, público da Feicoop pede Diretas Já e saída de Michel Temer',
        'arquivo' => 'single-post-2017-07-08-em-caminhada-publico-da-feicoop-pede-diretas-ja-e-saida-de-michel-temer.html',
        'data' => '2017-07-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-08-feicoop-e-aberta-em-clima-de-otimismo',
        'titulo' => 'Feicoop é aberta em clima de otimismo',
        'arquivo' => 'single-post-2017-07-08-feicoop-e-aberta-em-clima-de-otimismo.html',
        'data' => '2017-07-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-10-24a-feicoop-bate-recorde-de-publico-e-recebe-255-mil-visitantes',
        'titulo' => '24ª Feicoop bate recorde de público e recebe 255 mil visitantes',
        'arquivo' => 'single-post-2017-07-10-24a-feicoop-bate-recorde-de-publico-e-recebe-255-mil-visitantes.html',
        'data' => '2017-07-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-10-coletivo-a-cara-da-rua-traz-jovens-porto-alegrenses-para-a-feicoop',
        'titulo' => 'Coletivo A Cara da Rua traz jovens porto-alegrenses para a Feicoop',
        'arquivo' => 'single-post-2017-07-10-coletivo-a-cara-da-rua-traz-jovens-porto-alegrenses-para-a-feicoop.html',
        'data' => '2017-07-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-10-olivio-dutra-arrasta-multidao-pelos-corredores-da-feicoop',
        'titulo' => 'Olívio Dutra arrasta multidão pelos corredores da Feicoop',
        'arquivo' => 'single-post-2017-07-10-olivio-dutra-arrasta-multidao-pelos-corredores-da-feicoop.html',
        'data' => '2017-07-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-10-vereadora-torna-se-referencia-na-luta-pelo-empoderamento-feminino',
        'titulo' => 'Vereadora torna-se referência na luta pelo empoderamento feminino',
        'arquivo' => 'single-post-2017-07-10-vereadora-torna-se-referencia-na-luta-pelo-empoderamento-feminino.html',
        'data' => '2017-07-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-13-feira-dos-fabricantes-da-serra-e-do-artesanato-de-santa-mariars',
        'titulo' => 'FEIRA  DOS   FABRICANTES  DA  SERRA E  DO ARTESANATO  DE  SANTA  MARIA/RS',
        'arquivo' => 'single-post-2017-07-13-feira-dos-fabricantes-da-serra-e-do-artesanato-de-santa-mariars.html',
        'data' => '2017-07-13',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-07-14-arquidiocese-de-santa-maria-projeto-esperancacooesperanca-15081987-15082017',
        'titulo' => 'ARQUIDIOCESE DE SANTA MARIA
PROJETO ESPERANÇA/ COOESPERANÇA
15/08/1987 – 15/08/2017',
        'arquivo' => 'single-post-2017-07-14-arquidiocese-de-santa-maria-projeto-esperancacooesperanca-15081987-15082017.html',
        'data' => '2017-07-14',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-08-31-42a-feira-da-primavera',
        'titulo' => '42ª FEIRA DA PRIMAVERA',
        'arquivo' => 'single-post-2017-08-31-42a-feira-da-primavera.html',
        'data' => '2017-08-31',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-09-22-25a-feicoop-comeca-a-ser-planejada-neste-final-de-semana',
        'titulo' => '25ª Feicoop começa a ser planejada neste final de semana',
        'arquivo' => 'single-post-2017-09-22-25a-feicoop-comeca-a-ser-planejada-neste-final-de-semana.html',
        'data' => '2017-09-22',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-09-26-compartilhe-a-viagem',
        'titulo' => 'Compartilhe a viagem',
        'arquivo' => 'single-post-2017-09-26-compartilhe-a-viagem.html',
        'data' => '2017-09-26',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-09-26-feira-ana-primavesi',
        'titulo' => 'FEIRA ANA PRIMAVESI',
        'arquivo' => 'single-post-2017-09-26-feira-ana-primavesi.html',
        'data' => '2017-09-26',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-10-03-2o-nucleo-do-cpers-realiza-caminhada-luminosa-nesta-terca-feira-3',
        'titulo' => '2º Núcleo do CPERS realiza Caminhada Luminosa nesta terça-feira (3)',
        'arquivo' => 'single-post-2017-10-03-2o-nucleo-do-cpers-realiza-caminhada-luminosa-nesta-terca-feira-3.html',
        'data' => '2017-10-03',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-11-13-10-milhoes-de-estrelas',
        'titulo' => '10 Milhões de Estrelas',
        'arquivo' => 'single-post-2017-11-13-10-milhoes-de-estrelas.html',
        'data' => '2017-11-13',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-11-13-30-anos-do-projeto-esperancacooesperanca',
        'titulo' => '30 Anos do Projeto Esperança/Cooesperança',
        'arquivo' => 'single-post-2017-11-13-30-anos-do-projeto-esperancacooesperanca.html',
        'data' => '2017-11-13',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2017-12-22-sabado-23-e-dia-de-feirao-natalino-em-santa-maria',
        'titulo' => 'Sábado (23) é dia de Feirão Natalino em Santa Maria',
        'arquivo' => 'single-post-2017-12-22-sabado-23-e-dia-de-feirao-natalino-em-santa-maria.html',
        'data' => '2017-12-22',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-03-22-22-de-marco-dia-mundial-da-agua',
        'titulo' => '22 de março! DIA MUNDIAL DA ÁGUA',
        'arquivo' => 'single-post-2018-03-22-22-de-marco-dia-mundial-da-agua.html',
        'data' => '2018-03-22',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-03-28-feirao-de-pascoa',
        'titulo' => 'FEIRÃO DE PÁSCOA',
        'arquivo' => 'single-post-2018-03-28-feirao-de-pascoa.html',
        'data' => '2018-03-28',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-03-28-feliz-pascoa',
        'titulo' => 'FELIZ PÁSCOA',
        'arquivo' => 'single-post-2018-03-28-feliz-pascoa.html',
        'data' => '2018-03-28',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-04-12-feirao-especial',
        'titulo' => 'Feirão Especial',
        'arquivo' => 'single-post-2018-04-12-feirao-especial.html',
        'data' => '2018-04-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-04-12-lancamento-do-livro',
        'titulo' => 'Lançamento do Livro',
        'arquivo' => 'single-post-2018-04-12-lancamento-do-livro.html',
        'data' => '2018-04-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-04-12-roda-de-conversa',
        'titulo' => 'Roda de Conversa',
        'arquivo' => 'single-post-2018-04-12-roda-de-conversa.html',
        'data' => '2018-04-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-04-17-cpers-promove-plenaria-em-santa-maria-sobre-riscos-da-terceirizacao',
        'titulo' => 'CPERS promove plenária, em Santa Maria, sobre riscos da terceirização',
        'arquivo' => 'single-post-2018-04-17-cpers-promove-plenaria-em-santa-maria-sobre-riscos-da-terceirizacao.html',
        'data' => '2018-04-17',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-04-17-irma-lourdes-dill-denuncia-arbitrariedade-de-fiscalizacao-contra-pequenos-produtores-rura',
        'titulo' => 'Irmã Lourdes Dill denuncia arbitrariedade de fiscalização contra pequenos produtores rurais',
        'arquivo' => 'single-post-2018-04-17-irma-lourdes-dill-denuncia-arbitrariedade-de-fiscalizacao-contra-pequenos-produtores-rura.html',
        'data' => '2018-04-17',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-04-18-cpers-organiza-a-categoria-para-lutar-contra-a-terceirizacao',
        'titulo' => 'CPERS organiza a categoria para lutar contra a terceirização',
        'arquivo' => 'single-post-2018-04-18-cpers-organiza-a-categoria-para-lutar-contra-a-terceirizacao.html',
        'data' => '2018-04-18',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-04-30-feirao-dia-das-maes',
        'titulo' => 'FEIRÃO DIA DAS MÃES',
        'arquivo' => 'single-post-2018-04-30-feirao-dia-das-maes.html',
        'data' => '2018-04-30',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-05-11-economia-solidaria-na-tribuna-livre-da-camara-irma-lourdes-dill-cobra-respeito-a-agricult',
        'titulo' => 'ECONOMIA SOLIDÁRIA. Na Tribuna Livre da Câmara, Irmã Lourdes Dill cobra respeito à Agricultura Famil',
        'arquivo' => 'single-post-2018-05-11-economia-solidaria-na-tribuna-livre-da-camara-irma-lourdes-dill-cobra-respeito-a-agricult.html',
        'data' => '2018-05-11',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-06-25-documentario-sobre-economia-solidaria-e-apresentado-em-plenario-geral-sobre-a-25a-feicoop',
        'titulo' => 'Documentário sobre Economia Solidária é apresentado em Plenário Geral sobre a 25ª Feicoop',
        'arquivo' => 'single-post-2018-06-25-documentario-sobre-economia-solidaria-e-apresentado-em-plenario-geral-sobre-a-25a-feicoop.html',
        'data' => '2018-06-25',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-06-25-plenaria-geral-em-preparacao-a-25a-feicoop-sera-realizada-neste-domingo-24',
        'titulo' => 'Plenária Geral em preparação a 25ª Feicoop será realizada neste domingo (24)',
        'arquivo' => 'single-post-2018-06-25-plenaria-geral-em-preparacao-a-25a-feicoop-sera-realizada-neste-domingo-24.html',
        'data' => '2018-06-25',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-07-10-confira-a-carta-de-orientacoes-aos-visitantes-da-25a-feicoop',
        'titulo' => 'Confira a carta de orientações aos visitantes da 25ª Feicoop',
        'arquivo' => 'single-post-2018-07-10-confira-a-carta-de-orientacoes-aos-visitantes-da-25a-feicoop.html',
        'data' => '2018-07-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-07-12-artesaos-de-bage-participam-da-feicoop-pela-primeira-vez',
        'titulo' => 'Artesãos de Bagé participam da Feicoop pela primeira vez',
        'arquivo' => 'single-post-2018-07-12-artesaos-de-bage-participam-da-feicoop-pela-primeira-vez.html',
        'data' => '2018-07-12',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-07-13-portaria-para-25a-feicoop',
        'titulo' => 'Portaria para 25ª FEICOOP',
        'arquivo' => 'single-post-2018-07-13-portaria-para-25a-feicoop.html',
        'data' => '2018-07-13',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-07-16-abertura-oficial-celebra-os-25-anos-de-sucesso-da-feicoop',
        'titulo' => 'Abertura Oficial celebra os 25 anos de sucesso da Feicoop',
        'arquivo' => 'single-post-2018-07-16-abertura-oficial-celebra-os-25-anos-de-sucesso-da-feicoop.html',
        'data' => '2018-07-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-07-16-feicoop-bate-recorde-de-publico-com-302-mil-visitantes',
        'titulo' => 'Feicoop bate recorde de público com 302 mil visitantes',
        'arquivo' => 'single-post-2018-07-16-feicoop-bate-recorde-de-publico-com-302-mil-visitantes.html',
        'data' => '2018-07-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-07-16-jubileus-sao-comemorados-com-bolo-gigante-na-feicoop',
        'titulo' => 'Jubileus são comemorados com bolo gigante na Feicoop',
        'arquivo' => 'single-post-2018-07-16-jubileus-sao-comemorados-com-bolo-gigante-na-feicoop.html',
        'data' => '2018-07-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-07-27-campanha-internacional-compartilhe-a-viagem-desembarca-em-santa-maria',
        'titulo' => 'Campanha internacional "Compartilhe a Viagem" desembarca em Santa Maria',
        'arquivo' => 'single-post-2018-07-27-campanha-internacional-compartilhe-a-viagem-desembarca-em-santa-maria.html',
        'data' => '2018-07-27',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-07-31-musica-do-grito-dos-excluidos-2018',
        'titulo' => 'MÚSICA DO GRITO DOS EXCLUÍDOS 2018',
        'arquivo' => 'single-post-2018-07-31-musica-do-grito-dos-excluidos-2018.html',
        'data' => '2018-07-31',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-08-08-bancarios-de-santa-maria-e-regiao-rejeitam-proposta-da-fenaban',
        'titulo' => 'Bancários de Santa Maria e região rejeitam proposta da Fenaban',
        'arquivo' => 'single-post-2018-08-08-bancarios-de-santa-maria-e-regiao-rejeitam-proposta-da-fenaban.html',
        'data' => '2018-08-08',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-08-10-28o-seminario-estadual-de-alternativas-a-cultura-do-fumo',
        'titulo' => '28º Seminário Estadual de Alternativas à Cultura do Fumo',
        'arquivo' => 'single-post-2018-08-10-28o-seminario-estadual-de-alternativas-a-cultura-do-fumo.html',
        'data' => '2018-08-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-08-10-feliz-dia-dos-pais',
        'titulo' => 'Feliz Dia dos Pais',
        'arquivo' => 'single-post-2018-08-10-feliz-dia-dos-pais.html',
        'data' => '2018-08-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-08-10-medalha-jubileu-de-prata',
        'titulo' => 'MEDALHA JUBILEU DE PRATA',
        'arquivo' => 'single-post-2018-08-10-medalha-jubileu-de-prata.html',
        'data' => '2018-08-10',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-08-17-resistencia-democratica-unidos-pela-justica-e-paz',
        'titulo' => 'Resistência democrática, unidos pela justiça e paz!',
        'arquivo' => 'single-post-2018-08-17-resistencia-democratica-unidos-pela-justica-e-paz.html',
        'data' => '2018-08-17',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-09-03-novos-caminhos-quais-caminhos-levam-a-justica',
        'titulo' => 'Novos Caminhos – quais
caminhos levam á justiça?”',
        'arquivo' => 'single-post-2018-09-03-novos-caminhos-quais-caminhos-levam-a-justica.html',
        'data' => '2018-09-03',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-10-16-coracao-de-menino-cheio-de-esperanca-voz-de-pai-amigo-e-olhar-de-avo',
        'titulo' => 'Coração de menino cheio de esperança, voz de pai amigo e olhar de avó”.',
        'arquivo' => 'single-post-2018-10-16-coracao-de-menino-cheio-de-esperanca-voz-de-pai-amigo-e-olhar-de-avo.html',
        'data' => '2018-10-16',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-2018-11-01-o-projeto-esperanca-participa-das-comemoracoes-dos-30-anos-da-constituicao-brasileira',
        'titulo' => 'O Projeto Esperança participa das comemorações dos 30 anos da Constituição Brasileira',
        'arquivo' => 'single-post-2018-11-01-o-projeto-esperanca-participa-das-comemoracoes-dos-30-anos-da-constituicao-brasileira.html',
        'data' => '2018-11-01',
        'historico' => '1',
    ],
    [
        'tipo' => 'post',
        'slug' => 'single-post-30feicoop2024',
        'titulo' => '32ª FEICOOP – 2026 – 10 a 12 de Julho - 2026',
        'arquivo' => 'single-post-30feicoop2024.html',
    ],
];
